# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Consortium for the Advancement of Scientific Software
email: cass-steering-committee@email.ornl.gov
description: >- # this means to ignore newlines until "baseurl:"
  A federation of member organizations dedicated to the stewardship and advancement of the scientific software ecosystem.
baseurl: "/new" # the subpath of your site, e.g. /blog
url: "https://cass.community" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  CASS-Community

# Build settings
#theme: minima
theme: minimal-mistakes-jekyll

# Many configuration items for Minimal Mistakes.
# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/ for details.

#minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
minimal_mistakes_skin: "air"

# This subtitle is too long
#subtitle:   A federation of member organizations dedicated to the stewardship and advancement of the scientific software ecosystem.
name: The CASS Community

repository: cass-community/cass-community-new

teaser: /assets/images/cass-small-logo.png
logo: /assets/images/cass-logo.png
og_image: /assets/images/cass-logo.png

# Add site search, eventually
# Add web analytics, eventually

collections:
  wg:
    output: true
    permalink: /:collection/:slug
  sw:
    output: true
    permalink: /:collection/:slug

defaults:
  # wg -- working groups
  - scope:
      path: ""
      type: "wg"
    values:
      layout: "single"
      author_profile: true
      comments: false
  # sw -- software products
  - scope:
      path: ""
      type: "sw"
    values:
      layout: "single"
      author_profile: false
      comments: false

footer:
  links:
    - label: "Email Us"
      icon: "fas fa-envelope"
      url:  "mailto:cass-steering-committee@email.ornl.gov"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/CASS-Community"

# This is needed to generate output for future events
future: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Mute some deprecation warnings from older versions of jekyll-sass-converter
# as suggested by https://github.com/mmistakes/minimal-mistakes/issues/4054#issuecomment-1396536483
sass:
  quiet_deps: true