# Add new HPC Best Practices webinar event from ideas-productivity.org site
name: "HPC-BP: add new event from ideas-productivity.org"

on:
  workflow_dispatch:
    inputs:
      event-file:
        description: 'Basename of HPC-BP event on ideas-productivity.org (without extension)'
        required: true
        type: string

jobs:
  hpcbp-event-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      # - name: Check the file is there
      #   run: |
      #     ls -l _events/hpcbp-webinars/${{ inputs.event-file }}.md || :

      - name: Download the new event article
        uses: carlosperate/download-file-action@v2
        with:
          file-url: https://raw.githubusercontent.com/ideas-productivity/ideas-productivity.github.io/refs/heads/main/_events/hpcbp-webinars/${{ inputs.event-file }}.md
          location: '_events/hpcbp-webinars'
          file-name: ${{ inputs.event-file }}.md

      # - name: Check the file is there
      #   run: |
      #     ls -l _events/hpcbp-webinars/${{ inputs.event-file }}.md || :

      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          title: Add new HPC-BP webinar event
          branch: ${{ github.actor }}-hpcbp-new-event
          branch-suffix: timestamp
          assignees: ${{ github.actor }}
          commit-message: "Adding or updating HPC-BP webinar event from the ideas-productivity.org website"
          body: "Adding or updating HPC-BP webinar event from the ideas-productivity.org website"
          labels: |
            Section: events
            content update

      - name: Check PR results
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"

      # Hold off on the auto-merge until we're confident that the rest is working properly
      # NOTE: requires special privs to merge PRs (expecting a "PR_MERGE_PAT" secret)
      # - name: Merge PR
      #   if: ${{ steps.cpr.outputs.pull-request-number }}
      #   env:
      #     GH_TOKEN: ${{ secrets.PR_MERGE_PAT }}
      #   run: |
      #     gh pr merge ${{ steps.cpr.outputs.pull-request-number }} --merge --auto --body "Automatically merging script-generated event"
            